name: Compile Resume

on:
  push:
    branches: [ main ]
    paths:
      - "*.tex"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Latex Install
        run: sudo apt-get install texlive-xetex && sudo apt-get install texlive
        shell: bash

      - name: Compile
        run: xelatex resume.tex
        shell: bash

      - name: Git Setup
        run: git config user.name "LaTeX Compiler Action" && git config user.email "github-actions@github.com"

      - name: Commit
        run: git add resume.pdf && git commit -m "Update Resume" && git push
        shell: bash
